[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Lattice2D = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
ClassicalMonteCarlo = "faaa8aa3-7fc9-41cf-84af-9d0c24f78989"
LatticeCore = "84b1cbd8-bc58-4618-bc4f-b46a399f49f1"

[sources]
Lattice2D = {url = "https://github.com/sotashimozono/Lattice2D.jl.git", rev = "v0.2.3"}
ClassicalMonteCarlo = {path = ".."}
LatticeCore = {url = "https://github.com/sotashimozono/LatticeCore.jl.git", rev = "v0.7.3"}
